# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
                ('bio', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('landing_page', models.ImageField(blank=True, upload_to='landing_pages/')),
                ('Usability', models.IntegerField(default=0)),
                ('Design', models.IntegerField(default=0)),
                ('Content', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Project'),
        ),
    ]
