# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desciption', models.CharField(max_length=30)),
                ('landing_page', models.ImageField(upload_to='landing_pages')),
            ],
        ),
    ]
