# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Usability',
            new_name='usability',
        ),
    ]
